Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBrackets: no_space
